# Generated by Django 6.0.3 on 2026-04-09 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
